# Generated by Django 4.2.5 on 2023-10-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_player_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fullname',
            new_name='name',
        ),
    ]
