# Generated by Django 4.2.5 on 2023-10-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_rename_fullname_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='username',
            new_name='product',
        ),
    ]
