# Generated by Django 4.2.5 on 2023-10-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_rename_username_traveler_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='product',
            new_name='username',
        ),
    ]
