# Generated by Django 4.2.5 on 2023-10-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_rename_product_traveler_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
