# Generated by Django 4.2.5 on 2023-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_player_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
    ]
