# Generated by Django 4.2.5 on 2023-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_alter_player_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
